-- Pod schema: one copy of this schema per bioregion (`pod_<slug>`), applied
-- by the migration runner after `CREATE SCHEMA IF NOT EXISTS pod_<slug>`
-- with `search_path` scoped to `pod_<slug>, public` (see
-- packages/db/src/migrate.ts). Table names below are unqualified.
--
-- Id strategy (per docs/plans/2026-09-22-mvp-plan.md Task 4):
--   * text primary key, generated by services: events.id, rounds.id,
--     proposals.id, ballots.id, disputes.id, offers.id.
--   * bigint generated always as identity (append-only logs): vac_issuance_log.id,
--     adjustments.id, ledger_entries.id.
--   * natural keys elsewhere: members.did, edge_commitments.commitment,
--     witness_refs.digest, policy_versions.version, groups.did,
--     enterprises.did, accounts.did, records.uri.
--   * composite/derived keys: acceptance_rules.enterprise_did (1:1 with
--     enterprises), pos_grants (enterprise_did, provider), commitments.id
--     (bigint identity — an enterprise may re-sign its commitment over time).

CREATE TABLE IF NOT EXISTS members (
  did text PRIMARY KEY,
  tier text NOT NULL,
  vmc_grant_digest text,
  vmc_ack_digest text,
  "grant" jsonb,
  ack jsonb,
  valid_until timestamptz,
  joined_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS members_tier_idx ON members (tier);

CREATE TABLE IF NOT EXISTS edge_commitments (
  commitment text PRIMARY KEY,
  scope text NOT NULL,
  witnessed boolean NOT NULL DEFAULT false,
  witness_ref text,
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS witness_refs (
  digest text PRIMARY KEY,
  event_id text,
  convener_did text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS events (
  id text PRIMARY KEY,
  title text NOT NULL,
  starts_at timestamptz,
  ends_at timestamptz,
  place_id text,
  conveners jsonb NOT NULL DEFAULT '[]'::jsonb,
  task_document jsonb,
  task_digest text,
  attestation boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS vac_issuance_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  subject_did text NOT NULL,
  actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  tier text,
  policy_version integer,
  explanation jsonb,
  credential jsonb,
  issued_at timestamptz NOT NULL DEFAULT now(),
  valid_until timestamptz,
  revoked_at timestamptz
);

CREATE TABLE IF NOT EXISTS policy_versions (
  version integer PRIMARY KEY,
  policy jsonb NOT NULL,
  signed_at timestamptz
);

CREATE TABLE IF NOT EXISTS groups (
  did text PRIMARY KEY,
  name text NOT NULL,
  description text,
  contact text,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rounds (
  id text PRIMARY KEY,
  title text NOT NULL,
  pool numeric(14, 2),
  unit text,
  opens_at timestamptz,
  closes_at timestamptz,
  eligibility jsonb,
  status text NOT NULL DEFAULT 'draft',
  tally jsonb,
  published_at timestamptz
);

CREATE TABLE IF NOT EXISTS proposals (
  id text PRIMARY KEY,
  round_id text NOT NULL,
  title text NOT NULL,
  summary text,
  budget numeric(14, 2),
  lead_did text,
  place_id text,
  record jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS proposals_round_id_idx ON proposals (round_id);

CREATE TABLE IF NOT EXISTS ballots (
  id text PRIMARY KEY,
  round_id text NOT NULL,
  voter_key text NOT NULL,
  ballot jsonb NOT NULL,
  signature text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ballots_round_id_idx ON ballots (round_id);

CREATE TABLE IF NOT EXISTS adjustments (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  round_id text,
  proposal_id text,
  steward_did text,
  delta numeric(14, 2),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS enterprises (
  did text PRIMARY KEY,
  name text NOT NULL,
  categories jsonb NOT NULL DEFAULT '[]'::jsonb,
  accepts_local_credit boolean NOT NULL DEFAULT false,
  acceptance_share numeric(14, 2),
  steward_dids jsonb NOT NULL DEFAULT '[]'::jsonb,
  place_id text,
  owner_did text,
  record jsonb
);

CREATE TABLE IF NOT EXISTS acceptance_rules (
  enterprise_did text PRIMARY KEY REFERENCES enterprises(did),
  rules jsonb,
  ceiling numeric(14, 2),
  offline_allowance numeric(14, 2)
);

CREATE TABLE IF NOT EXISTS accounts (
  did text PRIMARY KEY,
  kind text NOT NULL,
  limit_band text,
  credit_limit numeric(14, 2),
  balance numeric(14, 2) NOT NULL DEFAULT 0,
  opened_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  payer_did text,
  payee_did text,
  amount numeric(14, 2) NOT NULL,
  unit text,
  invoice text,
  request jsonb,
  "authorization" jsonb,
  receipt jsonb,
  external_tender jsonb,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ledger_entries_payer_did_idx ON ledger_entries (payer_did);
CREATE INDEX IF NOT EXISTS ledger_entries_payee_did_idx ON ledger_entries (payee_did);

CREATE TABLE IF NOT EXISTS commitments (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  enterprise_did text NOT NULL,
  text text,
  signed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pos_grants (
  enterprise_did text NOT NULL,
  provider text NOT NULL,
  "grant" jsonb,
  PRIMARY KEY (enterprise_did, provider)
);

CREATE TABLE IF NOT EXISTS disputes (
  id text PRIMARY KEY,
  subject_digest text,
  filed_by text,
  reason text,
  status text NOT NULL DEFAULT 'open',
  adjudication jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS records (
  uri text PRIMARY KEY,
  collection text NOT NULL,
  bioregion text,
  place_id text,
  author_did text,
  record jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS records_collection_idx ON records (collection);
CREATE INDEX IF NOT EXISTS records_place_id_idx ON records (place_id);

CREATE TABLE IF NOT EXISTS offers (
  id text PRIMARY KEY,
  enterprise_did text,
  kind text NOT NULL CHECK (kind IN ('offer', 'need')),
  record jsonb
);
