-- Platform schema: control plane tables shared across all pods.
-- Id strategy: `pods.slug` is the natural primary key (globally unique per
-- the tenancy rule); `pod_keys` is keyed by (slug, kid) since a pod may
-- rotate to multiple key ids over its lifetime; `registry_entries` mirrors
-- one row per pod (slug); `tenant_zero_runs` and `relay_messages` are
-- generated by the runner/services, so they use identity columns
-- (`tenant_zero_runs.id` bigint identity; `relay_messages.seq` bigint
-- identity, paired with `channel` as the primary key so a relay channel's
-- messages are strictly ordered).
-- This file runs with search_path already scoped to `platform, public` by
-- the migration runner (see packages/db/src/migrate.ts), so table names
-- below are unqualified.

CREATE TABLE IF NOT EXISTS pods (
  slug text PRIMARY KEY,
  did text NOT NULL,
  name text NOT NULL,
  manifest jsonb NOT NULL,
  manifest_hash text,
  status text NOT NULL DEFAULT 'provisioning',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pod_keys (
  slug text NOT NULL REFERENCES pods(slug),
  kid text NOT NULL,
  public_key_multibase text NOT NULL,
  encrypted_private_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (slug, kid)
);

CREATE TABLE IF NOT EXISTS registry_entries (
  slug text PRIMARY KEY REFERENCES pods(slug),
  did text NOT NULL,
  anchors jsonb NOT NULL DEFAULT '[]'::jsonb,
  accepted_issuers jsonb NOT NULL DEFAULT '[]'::jsonb,
  vocab_version text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tenant_zero_runs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  ok boolean,
  report jsonb
);

CREATE TABLE IF NOT EXISTS relay_messages (
  channel text NOT NULL,
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  sender text,
  body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (channel, seq)
);

CREATE INDEX IF NOT EXISTS relay_messages_channel_seq_idx ON relay_messages (channel, seq);
